### ISSUE TITLE
打包为dist并部署到nginx后，前端无法显示实时聊天内容

### ISSUE THREAD

**Issue by sensite** [hncboy/ai-beehive#111]
打包为dist并部署到nginx后，前端无法显示实时聊天内容：
1、必须等后端的内容回复完成后，才会渲染到页面
2、在dev开发环境，没有问题

在windows启动nginx，存在同样的问题，所以原因可能为：
1、dist打包后，出了问题
2、nginx跨域转发时，出了问题

以下是我的nginx跨域转发设置：
server {
    listen       3001;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html/chatgpt-web-java/chatgpt-shuowen;
        index  index.html index.htm;
    }

    location /api/ {
        # 跨域转发：
        # 1、调整了原来的端口号，后端端口号调整为了3000，前端用户端调整为了3001
        proxy_pass http://xxx:3000/;
        # 测试禁用缓存：
        # 1、前端项目：服务端部署后，聊天时回复内容无法动态显示，需要等完成后一次性显示
        # proxy_no_cache any;
    }
}

**Comment by hncboy** [comment]
proxy_buffering off;

**Comment by sensite** [comment]
thanks!
